# T2KDE reproduction training - 400 epochs - 03/24/2026

# ===================================================
# Data configurations

data_file: /share/lazy/qibinlei/recoTrackNPV_jets_pubindices_1000bins_incbounds_Target_Y_split.h5
output_file_path: /data/home/matmauro/codice/PV-Finder/outputs/

# ===================================================
# Training configurations

device_id: 0
n_events: 51000
train_split: [0.7, 0.25, 0.05]
n_epochs: 400
batch_size: 128
num_workers: 16
learning_rate: 0.001
asymmetry_param: 2.5

save_weights: True
save_frequency: 10
save_folder: /data/home/matmauro/codice/PV-Finder/model_weights/03_24_2026/

experimentname: "ATLAS 2025 Reproduction - Tracks to KDE"
runname: "reproduction_KDE_A_z_400ep"

# ===================================================
# Model configurations

model_class: tracks-to-KDE
model_type: MaskedDNN

models_config:
    MaskedDNN:
        input_size: 7
        hidden_nodes: [100, 100, 100, 100, 100]
        output_size: 1000
        leaky_param: 0.01
        use_bn: False
        use_drop: False
        maskVal: -240.
        predScaleFactor: 0.001
        out_idx: 0
        allow_negative_output: False

continue_prior: False
